# promt colors I used:
# #06969A (petrol)
# #86BBD8 (light blue)
# #33658A (dark blue)
# #DA627D (petrol red)
# #FCA17D (apreco)
# #9A348E (purple)

format = """
[î‚¶](#9A348E)\
$os\
$username\
[î‚°](bg:#DA627D fg:#9A348E)\
$directory\
[î‚°](fg:#DA627D bg:#FCA17D)\
$git_state\
[î‚°](fg:#FCA17D bg:#86BBD8)\
$git_branch\
$git_status\
[î‚°](fg:#86BBD8 bg:#06969A)\
$kubernetes\
[î‚´](fg:#06969A)\
$fill\
[î‚¶](fg:black)\
$status\
[î‚²](fg:#86BBD8 bg:black)\
$nodejs\
$azure\
$python\
$terraform\
$lua\
$rust\
[î‚²](fg:#06969A bg:#86BBD8)\
$openstack\
$cmd_duration\
[î‚²](fg:#33658A bg:#06969A)\
$time\
[î‚´](fg:#33658A)\
$line_break\
$character
"""

command_timeout = 500

[fill]
symbol = "Â·"

# Disable the blank line at the start of the prompt
# add_newline = false

# You can also replace your username with a neat symbol like ï„   or disable this
# and use the os module below
[username]
show_always = true
style_user = "bg:#9A348E"
style_root = "bg:#9A348E"
format = '[$user ]($style)'
disabled = false

# An alternative to the username module which displays a symbol that
# represents the current operating system
[os]
style = "bg:#9A348E"
disabled = true # Disabled by default

[directory]
style = "bg:#DA627D"
format = "[ $path ]($style)"
truncation_length = 100
truncation_symbol = "â€¦/"

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"Downloads" = "ï€™ "
"Music" = "ó°š "
"Pictures" = "ï€¾ "
"Movies" = "ó°Ÿ "
# Keep in mind that the order matters. For example:
# "Important Documents" = " ó°ˆ™ï„ª "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important ó°ˆ™ " = " ó°ˆ™ï„ª "

[c]
symbol = "î˜ "
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[docker_context]
symbol = "ïŒˆ "
style = "bg:#06969A"
format = '[ $symbol $context ]($style) $path'

[elixir]
symbol = "î‰µ "
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[elm]
symbol = "î˜¬ "
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

# [git_state]
# format = '[\($state( $progress_current of $progress_total)\)]($style) '
# cherry_pick = '[ğŸ’ PICKING](bold red)'
#
[git_branch]
symbol = "ï˜"
style = "bg:#86BBD8"
format = '[ $symbol $branch ]($style)'

# [git_status]
# style = "bg:#FCA17D"
# untracked = ""
# format = '([\[$conflicted$deleted$renamed$modified$staged$behind\]]($style))'
# modified = '*'
# # format = '[$all_status$ahead_behind ]($style)'
[git_status]
ahead = "â‡¡${count} "
diverged = "â‡•â‡¡${ahead_count}â‡£${behind_count} "
behind = "â‡£${count} "
modified = '[!$count](bg:#86BBD8) '
staged = "+${count} "
untracked = "?${count} "
stashed = 'ğŸ“¦ ${count} '
up_to_date = '[âœ“](green bg:#86BBD8) '
style = "bg:#86BBD8"
format = "[$all_status$ahead_behind]($style)"

[golang]
symbol = "î˜§ "
style = "bg:#86BBD8"
format = '[ $symbol($version) ]($style)'

[kubernetes]
disabled = false
style = "bg:#33658A"
format = '[ $symbol$context ]'

[rust]
symbol = "î¨"
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[time]
disabled = false
time_format = "%T" # Hour:Minute Format
style = "bg:#33658A"
format = '[ $time ]($style)'

[azure]
disabled = false
format = 'on [$symbol($subscription)]($style) '
symbol = 'î¯˜ '
style = "bg:#86BBD8"

[lua]
format = '[$symbol($version )]($style)'
style = "bg:#86BBD8"

[openstack]
format = '[$symbol$cloud(\($project\))]($style)'
style = "bg:#06969A"
# symbol = 'â˜ï¸ '
symbol = 'ó°…Ÿ '

[terraform]
format = '[$symbol($version )]($style)'
style = "bg:#86BBD8"
symbol = 'ó±¢ '

[python]
style = "bg:#86BBD8"
pyenv_version_name = true
format = '[${symbol}${version}]($style)'

[cmd_duration]
style = "bg:#06969A"
# style = "bg:#86BBD8"
format = '[â± $duration]($style)'

[status]
disabled = false
style = "bg:#000000"
success_symbol = "[âœ”](green bg:black)"
symbol = "[âœ˜](red bg:black)"
format = '[$symbol$common_meaning$signal_name$maybe_int]($style)'
